### PR TITLE
fix case of sending a message with envelope.room being an inexistant …

### PR DESCRIPTION
**Pull request by shadiakiki1986**
fix case of sending a message with envelope.room being an inexistant user/channel name

### CODE REVIEW

**Comment by aoberoi** [comment]
@shadiakiki1986: thanks for the contribution. i took a quick look and it seems like even without your changes, the send call should not fail. your changes will add a helpful log message though. is that right?

**Comment by shadiakiki1986** [comment]
Hello. You're welcome. No, the send call does fail. If you comment out the `return` that I have after the log message, this is the result of `npm test`

```
  ...
  46 passing (132ms)
  1 failing

  1) Send Messages Should not fail for inexistant user:
     TypeError: Cannot read property 'send' of undefined
    at SlackBot.send (/home/shadi/Development/hubot-slack/src/slack.coffee:1:1)
    at Context.<anonymous> (/home/shadi/Development/hubot-slack/test/slack.coffee:105:30)
    at Test.Runnable.run (/home/shadi/Development/hubot-slack/node_modules/mocha/lib/runnable.js:211:32)
    at Runner.runTest (/home/shadi/Development/hubot-slack/node_modules/mocha/lib/runner.js:358:10)
    at /home/shadi/Development/hubot-slack/node_modules/mocha/lib/runner.js:404:12
    at next (/home/shadi/Development/hubot-slack/node_modules/mocha/lib/runner.js:284:14)
    at /home/shadi/Development/hubot-slack/node_modules/mocha/lib/runner.js:293:7
    at next (/home/shadi/Development/hubot-slack/node_modules/mocha/lib/runner.js:237:23)
    at Immediate.<anonymous> (/home/shadi/Development/hubot-slack/node_modules/mocha/lib/runner.js:261:5)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
  




npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/home/shadi/.nvm/versions/node/v7.1.0/bin/node" "/home/shadi/.nvm/versions/node/v7.1.0/bin/npm" "run" "mocha"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! hubot-slack@3.4.2 mocha: `mocha --compilers coffee:coffee-script/register  --require coffee-coverage/register-istanbul --reporter spec test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hubot-slack@3.4.2 mocha script 'mocha --compilers coffee:coffee-script/register  --require coffee-coverage/register-istanbul --reporter spec test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hubot-slack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --compilers coffee:coffee-script/register  --require coffee-coverage/register-istanbul --reporter spec test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hubot-slack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hubot-slack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shadi/Development/hubot-slack/npm-debug.log
npm ERR! Test failed.  See above for more details.

```

**Comment by shadiakiki1986** [comment]
Let me try to rebase and retest and see if commits after my PR already solve it

**Comment by shadiakiki1986** [comment]
So I dropped my commit, rebased with your master branch, and added the test from my commit.
Indeed, the send no longer fails for an inexistant user/room. This was possibly fixed somewhere.
Anyway, I couldn't figure out how to add an informative message like my older commit, so here is my PR updated to only contain the test case. My older commit inserted the message [here](https://github.com/slackapi/hubot-slack/blob/c0775f4f4a2e7718d3f0e1edb3a818b945485e41/src/slack.coffee#L225) by doing
```
    if not channel and not @client.getUserByName(envelope.room)
      @robot.logger.debug "Inexistant channel or username: #{envelope.room}. Aborting message #{msg}"
      return
```

**Comment by aoberoi** [comment]
@shadiakiki1986 this is extremely late feedback, so i do apologize.

i'd like to merge you test case. would you mind signing the CLA?

**Comment by shadiakiki1986** [comment]
No problem. I just signed the CLA

**Comment by aoberoi** [comment]
@shadiakiki1986 did you sign by visiting this URL: https://cla-assistant.io/slackapi/hubot-slack?pullRequest=308 ? i don't see your github name on the list of signatures.

**Comment by shadiakiki1986** [comment]
No I got the link from another pull request pointing to a form on google
docs. Anyway,  I followed your link now and signed again. Probably worth it
to put the link on the readme page

**Comment by aoberoi** [comment]
@shadiakiki1986 thanks! and i've noted your point, i thought having the status check in the PR would be enough but for future PRs the cla-assistant bot should also post a message.

i think that because of github's backed up queues this morning, there's some issues around updating branches from PRs. would you enable maintainers to update this pull request so i can manually merge?

**Comment by shadiakiki1986** [comment]
I clicked on the checkbox to allow edits from maintainers, but I got an error saying "could not perform this action at this time". I also noticed there's an update branch button now which I just clicked.

**Pull request merged**
