### PR TITLE
Add compatibility for Coffeescript 2 (and hubot 3)

### PR DESCRIPTION
**Pull request by phucnh**
###  Summary

This PR continues https://github.com/slackapi/hubot-slack/pull/528 works.
Make sure the classes in this code work in Coffeescript 2 (and with hubot 3).

A few of the semantic differences between Coffeescript 1 classes and ES2015 classes has introduced some backwards compatibility issues, as follows:
[Breaking Changes From CoffeeScript 1.x to 2](https://coffeescript.org/#unsupported-get-set)

Known Issue: This PR doesn't make hubot-slack work with hubot 2 in Coffeescript 2. Because hubot 2 still based on Coffeescript 1.

Refs: https://github.com/slackapi/hubot-slack/issues/526

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by phucnh** [comment]
Tests on nodejs <= 5 with envs are `HUBOT_VERSION="^3.0" COFFEESCRIPT_VERSION="^2.0"` because [the destructuring assignment syntax: `{fork} = child_process;](https://github.com/jashkenas/coffeescript/blob/71750554c3a94d276a5c5344d77292fff5205e49/lib/coffeescript/register.js#L61)



```
> mocha --compilers coffee:coffeescript/register --require coffee-coverage/register-istanbul --reporter spec test
"--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
/home/travis/build/slackapi/hubot-slack/node_modules/coffeescript/lib/coffeescript/register.js:61
    ({fork} = child_process);
     ^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/slackapi/hubot-slack/node_modules/coffeescript/register.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/slackapi/hubot-slack/node_modules/mocha/bin/_mocha:453:3
    at Array.forEach (native)
    at Object.<anonymous> (/home/travis/build/slackapi/hubot-slack/node_modules/mocha/bin/_mocha:445:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by mistydemeo** [comment]
@aoberoi Any chance we could get your review here? This would be really useful for me.

**Comment by seratch** [comment]
@phucnh 
Thank you for taking the time to make this PR. This looks great and is really amazing!

@aoberoi @stevengill @shaydewael 
I'll verify the details (just in case) again and merge this next week. Also, I would like to work on the next minor version (v4.8) later. I think enabling developers to use CoffeeScript 2 is quite helpful as the major version supports async/await in the language (it's not available in CoffeeScript 1.x!). Let me know if you have thoughts on this.

**Comment by seratch** [comment]
I've reverted this PR as it's not fully compatible with CoffeeScript 2 yet. I'm still positive to support CoffeeScript in future versions but for the next minor version (v4.8.0 - https://github.com/slackapi/hubot-slack/milestone/4), this improvement may be out of scope.

**Pull request merged**
