### PR TITLE
Accept DM'ed commands with or without bot name prefix

### PR DESCRIPTION
**Pull request by patcon**
See: https://github.com/hubotio/hubot/issues/1356

### CODE REVIEW

**Comment by aoberoi** [comment]
@patcon thanks for the contribution and my apologies for the late feedback!

i think this is a great idea. in fact, #291 seems to implement the same behavior. i also think the environment variable approach (discussed in hubotio/hubot#1356) in addition would be an even greater improvement.

if you can contribute some test code, i'd be happy to merge this. if you'd like help with getting that done, let me know.

**Comment by aoberoi** [comment]
ping, still open to this contribution!

**Comment by patcon** [comment]
gr... i gitted wrong

**Comment by patcon** [comment]
okie doke fixed

**Comment by aoberoi** [comment]
@shanedewael would merging this make your work in #465 more complicated? one opportunity to simplify i see is that instead of matching on the first letter of the channel ID, since we have the entire `conversations.info` object, we should be able to use `channel.is_im || channel.is_mpim` instead.

**Comment by shanedewael** [comment]
@aoberoi This should definitely be able to work with #465 - merge ahead 🎉

**Pull request merged**
